### PR TITLE
Accidental rewrite

### PR DESCRIPTION
**Pull request by rummik**
Hi!  Um, have a version 2?  :grin:

Changes include
- Full rewrite
- Promises!
- JSDoc headers
- Easily tested code (probably) (no unit tests included...sorry)

This should have roughly the same feature set as before, but if I forgot anything feel free to let me know and I'll bring it back.

### CODE REVIEW

**Comment by hobbyquaker** [comment]
Great PR, thanks! 👍 
I added automatic markdown generation from the jsdocs. Also did some linting with xo. 
As I'm lazy and still not into promises (and have no pain with callbacks) a question: do you see a possibility to make the methods work with promises _and_ callbacks? So i could remove the v1.0 hint from the readme. :)

**Comment by rummik** [comment]
Um.  Yes, any method that returns a promise could check to see if the last argument is a function and attach it to a promise chain.  This could also be done with a helper to reduce code duplication

**Comment by hobbyquaker** [comment]
motivated to work on that? :-)

**Comment by rummik** [comment]
Probably could.  I'm not sure when I'll set back down to work on LIRC-related things, but I'll do it then :+1:

**Pull request merged**
